route:
  receiver: "discord-webhook"
  group_wait: 10s
  repeat_interval: 1h

receivers:
  - name: "discord-webhook"
    discord_configs:
      - webhook_url: "https://discord.com/api/webhooks/1490003554545438761/Y3THqrWYibv1eibDp0XzSrLQSSinfgjbfXs_PAo5mSmYCYAtUb37NQlPMRO80BZiqiw4"
        send_resolved: true
        content: |
          🚨 **Alert Notification**

        title: '{{ template "discord.default.title" . }}'

        message: |
          {{ range .Alerts }}
          **Alert:** {{ .Labels.alertname }}
          **Severity:** {{ .Labels.severity }}
          **Instance:** {{ .Labels.instance }}
          **Summary:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          {{ end }}
